### ISSUE TITLE
Support to work on custom tag key name - WithCustomTagKey()

### ISSUE THREAD

**Issue by alok87** [m-mizutani/masq#18]
Please suggest if you are ok to add support for allowing any key name and not `masq` for tag keys. We want our code independent of the library of masking and we already have a tag name in existing in code which we want to plug.

**Current:** 
```go
type myRecord struct {
    Secret string `masq:"secret"`
}
```

**Proposal:** 
```go
type myRecord struct {
    Secret string `custommasqname:"secret"`
}
```

If ok, please suggest what requires change, would push the change. Thanks.

Thanks for building this clean interface around masking. You should evangelize this and bring it under  https://go.dev/wiki/Resources-for-slog?ref=blog.arcjet.com

**Comment by m-mizutani** [comment]
@alok87 
Thank you for your suggestion. I think it would be a good idea and I tried to implement the feature in https://github.com/m-mizutani/masq/pull/19 . How about the change?

**Comment by alok87** [comment]
add DefaultTagKey and take #19 and close this then. both works.

**Comment by m-mizutani** [comment]
Thank you for your comments and works. I merged https://github.com/m-mizutani/masq/pull/19 and it will be in next release.
