### ISSUE TITLE
What needs to be added in zap custom handler to use masq?

### ISSUE THREAD

**Issue by alok87** [m-mizutani/masq#22]
Wanted some suggestions on how can we use masq in zap custom handler 
https://github.com/uber-go/zap/blob/master/exp/zapslog/handler.go

**Comment by alok87** [comment]
```go
// Apply replaceAttr if defined
	if h.replaceAttr != nil {
	  attr = h.replaceAttr(h.groups, attr)
	}
```

trying plugging this

**Comment by m-mizutani** [comment]
@alok87 Thank you for your suggestion. I would appreciate it if you could clarify your point a bit more. Could you please provide me with a use case involving the handler feature?

**Comment by m-mizutani** [comment]
@alok87 Do you mean that you would like to use `masq` in slog Handler of `zapslog` ? If so, `zapslog` should have `Resolve` and `ReplaceAttr` logic in the Handler.
https://cs.opensource.google/go/go/+/refs/tags/go1.23.3:src/log/slog/handler.go;l=467-519

**Comment by m-mizutani** [comment]
@alok87 How about this? Can I close the issue?

**Comment by m-mizutani** [comment]
Let me close the issue. Please reopen it if you need it yet.
